### ISSUE TITLE
Undeclared variable throws error in strict mode

### ISSUE THREAD

**Issue by nolan-m** [daniel-cottone/serverless-es-logs#124]
The variable `jsonSubString` is not declared in the function `buildSource`.  This is throwing an error when using this plugin with `serverless-webpack` which adds strict mode.

https://github.com/daniel-cottone/serverless-es-logs/blob/283eb348a79edbb4c9376f734dd1d0c3373b2037/templates/code/logsToEs.js#L111

**Comment by nolan-m** [comment]
Fixed in https://github.com/daniel-cottone/serverless-es-logs/pull/125

**Comment by nolan-m** [comment]
@daniel-cottone Any timeline for getting a new release with this fix?

**Comment by nolan-m** [comment]
@daniel-cottone Any update on a release?

**Comment by daniel-cottone** [comment]
@nolan-m this should be released with the latest version

**Comment by nolan-m** [comment]
Thank you very much!
