### ISSUE TITLE
Execution Role - Permissions

### ISSUE THREAD

**Issue by RyanCodes** [daniel-cottone/serverless-es-logs#145]
` An error occurred: EsLogsProcesserLambdaFunction - The provided execution role does not have permissions to call CreateNetworkInterface on EC2 (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: b9961307-18dd-11e9-980e-8b58ca234a14).`

I am getting the following when trying to deploy? Any ideas

**Comment by daniel-cottone** [comment]
@RyanCodes Can you post your `serverless.yml`? That would help me try to duplicate your issue.

**Comment by andrepintorj** [comment]
Hi @daniel-cottone I'm facing the exact same issue when trying to use the plugin. I *think* that when Lambdas are deployed on VPC, the execution role for the EsLogsProcesserLambdaFunction has to create an ENI to communicate...
