### ISSUE TITLE
Question about log forwarding

### ISSUE THREAD

**Issue by darlintonprauchner** [daniel-cottone/serverless-es-logs#268]
Hi!
I started to look at the code and I could not get to a conclusion about how the logs are forwarded to elastic search.

Are you using CloudWatch subscriptions feature, or, this plugin pushes each log manually to ES at runtime?

Thanks!

**Comment by daniel-cottone** [comment]
Hey @darlintonprauchner, this plugin works by creating a Cloudwatch log subscription for each log group, and a lambda that processes these logs and ships them to elasticsearch.
