### ISSUE TITLE
  Error: ENOENT: no such file or directory, open '/Users/xx/code/xxx-lambda-xxx/.build/.serverless/esLogsProcesser.zip'

### ISSUE THREAD

**Issue by aterreno** [daniel-cottone/serverless-es-logs#289]
Hi, 
I am witnessing this error which seems correlated to the fact that I am using the typescript plugin on my lambdas (I have other lambdas done in pure js and it's all good) 

```
plugins:
  - serverless-es-logs
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-domain-manager
  - serverless-add-api-key
  - serverless-iopipe-layers
``` 

that's my plugin section 

Any clue what is happening here?

**Comment by aterreno** [comment]
seems like the zip file is inside

`ls -la /Users/xxx/code/xxx-lambda-xxx/.serverless`

but not inside 

`ls -la /Users/xxx/code/xxx-lambda-xxx/.build/.serverless`

I wonder if it's the ts plugin building differently

**Comment by daniel-cottone** [comment]
@aterreno Sorry for the late response; I'm closing this for now. If this issue is still of interest to you, please open a new issue with a minimum reproducible example.

Thanks!
