### ISSUE TITLE
Is request report logging available?

### ISSUE THREAD

**Issue by ValiDraganescu** [daniel-cottone/serverless-es-logs#320]
Hi,

I searched in the docs and issues to find the answer to my question, but I did not found what I was looking for, specifically is this log send to elastic search? From what I see it doesn't and I would like to plot this duration, mermory used etc to a dashboard.
`REPORT RequestId: 4e352e1c-e997-4708-8a1e-eb40d9494be4 Duration: 1904.24 ms Billed Duration: 2000 ms Memory Size: 1024 MB Max Memory Used: 276 MB Init Duration: 2701.30 ms ` 

I also see this errors in the logs of the logger (nice pun here) 

`INFO Failed Items: [
{
    "index": {
        "_index": "dev-logs-2019.10.31",
        "_type": "serverless-es-logs",
        "_id": "35068670517148905662465861963755689593093688542227529757",
        "status": 400,
        "error": {
            "type": "mapper_parsing_exception",
            "reason": "failed to parse field [@event.location] of type [text] in document with id '35068670517148905662465861963755689593093688542227529757'",
            "caused_by": {
                "type": "illegal_state_exception",
                "reason": "Can't get text on a START_OBJECT at 1:124"
            }
        }
    }
},
...]`

I think that there is a mapping issue because in some logs there is a "location" property in a json object that has the type string (like "lat,lng") but on some other logs there is a location property like this `"location": {lat: 42, lng: 42}`

**Comment by daniel-cottone** [comment]
Hey @ValiDraganescu, you can use the `filterPattern` option to override the default filter pattern that is used: https://github.com/daniel-cottone/serverless-es-logs#filterpattern. I'm not sure if you'll be able to come up with a pattern that will work for the log messages and the reports though. Let me know if you do!

That error you're seeing is coming from Elasticsearch, which has some limitations around field types: you can't send properties to Elasticsearch with two different types. Looks like in your case you are trying to send both a string and an object.
