### ISSUE TITLE
Can I have variable date in index like logs-YYYY.MM.DD?

### ISSUE THREAD

**Issue by MrSpark2591** [daniel-cottone/serverless-es-logs#376]
In index filed, can I have the variable date as we follow index pattern like this:
logs-2020.01.27
Where it follows  pattern.
logs-YYYY.MM.DD
Is this one possible with this plugin?

**Comment by daniel-cottone** [comment]
@MrSpark2591 I'm not sure I follow; this is already the format of the date index pattern.

I'm closing this issue for now, if you are still interested in this issue please recreate the issue using the new issue template for further discussion.
