### ISSUE TITLE
Buffer() is deprecated due to security and usability issues. 

### ISSUE THREAD

**Issue by jraff** [daniel-cottone/serverless-es-logs#424]
Hello, thank you for this wonderful plugin, the only issue I am facing right now is that I'm seeing the following error in my lambda.

`DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.`

**Comment by daniel-cottone** [comment]
Hey @jraff, thanks for bringing this up. We should definitely fix this!
