### ISSUE TITLE
JSON logs

### ISSUE THREAD

**Issue by devotox** [daniel-cottone/serverless-es-logs#49]
How can we set the logFormat and remove the filterPattern?

**Comment by daniel-cottone** [comment]
You can't remove the filter pattern, it's required for a cloudwatch subscription. Could you explain what it is that you are trying to do?

**Comment by devotox** [comment]
We use winston for our logs and they are JSON strings. If you see in AWS console you can select JSON as the log format and the filter pattern is then removed

**Comment by daniel-cottone** [comment]
Check the latest release, https://github.com/daniel-cottone/serverless-es-logs/releases/tag/v1.2.0

You can now override the lambda subscription filter pattern. You probably want something like `[event]`.

**Comment by devotox** [comment]
@daniel-cottone Thank you for this update. I dont believe winston can write to console due to this issue
https://github.com/winstonjs/winston/issues/981

Have you ever been able to do this personally?

**Comment by daniel-cottone** [comment]
I haven't tried this with winston, but it's doable with [bunyan](https://github.com/trentm/node-bunyan).
