### ISSUE TITLE
Disable logs for some functions

### ISSUE THREAD

**Issue by devotox** [daniel-cottone/serverless-es-logs#63]
it seems there is a clash with serverless-warmup-plugin which causes the same index to be used

    "errorMessage": "{\"statusCode\":200,\"responseBody\":\"{\\\"took\\\":26,\\\"errors\\\":true,\\\"items\\\":[{\\\"index\\\":{\\\"_index\\\":\\\"cwl-stock-middleware-production-2018.10.01\\\",\\\"_type\\\":\\\"/aws/lambda/stock-middleware-production-warmup-plugin\\\",\\\"_id\\\":\\\"34307478538089366886714326327315175922272989826627862528\\\",\\\"status\\\":400,\\\"error\\\":{\\\"type\\\":\\\"illegal_argument_exception\\\",\\\"reason\\\":\\\"Rejecting mapping update to [cwl-stock-middleware-production-2018.10.01] as the final mapping would have more than 1 type: [/aws/lambda/stock-middleware-production-kinesis, /aws/lambda/stock-middleware-production-warmup-plugin]\\\"}}}]}\"}"

**Comment by devotox** [comment]
Actually this seems to be the problem with all functions in the same service

**Comment by devotox** [comment]
MY PR fixes the issue with ES 6.3 also we should probably look at allowing things like the timeout and memorySize to be configurable

**Comment by daniel-cottone** [comment]
I don't think this should be the default behavior. Wanting individual indices for functions seems useful but probably the default behavior should still be to send all logs to the same index, and could be overridden by a configuration option.

Another problem with this is that now we would have API Gateway logs going to the specified index but lambda function logs going to their own indices.

**Comment by devotox** [comment]
I understand what you are saying but Its only that using AWS ES6.3 (which is the default).
Everyone using this library will have their logs broken as you cannot have more than one function go to the same index anymore.

**Comment by daniel-cottone** [comment]
Right, this is a breaking change in 6.x: https://www.elastic.co/guide/en/elasticsearch/reference/6.0/removal-of-types.html

I still think the best approach is to have the default behavior be that all logs go to the same index, but have configuration options to support splitting the logs into different indices. We can create a custom type/source attribute as mentioned in the article to support this, and set `_type` to be something like `${service_name}_serverless_es_logs`.

**Comment by daniel-cottone** [comment]
I will raise a PR to fix the plugin for 6.3, and I'll leave it to you to clean up your PR if you want to add an option to split logs into different groups.

It also occurs to me I should add some contributing guidelines! 😄

**Comment by devotox** [comment]
Hahha. Well glad i could give you that insight at least.

I dont need it to be configurable per say. I just wanted it to work for 6.3.

What do you think about the timeout and memorySize being configurable or at least going down from 512. That seems high for all this is doing

**Comment by daniel-cottone** [comment]
Sure thing! Fixed in `2.0.0`: https://github.com/daniel-cottone/serverless-es-logs/releases/tag/v2.0.0

We can make those options configurable as well! Feel free to raise a PR for it

**Comment by devotox** [comment]
🙏 Thank you sir!
So quick... So flawless

**Comment by daniel-cottone** [comment]
💪
